function model = discreteCVmodel(q, r)
    % returns a structure that implements a discrete time CV model with
    % continuous time accelleration covariance q and positional
    % measurement with noise with covariance r, both in two dimensions.
    model.f = @(x, Ts) ...
    model.F = @(x, Ts) ...
    model.Q = @(x, Ts) ...
                    
    model.h = @(x) ...
    model.H = @(x) ...
    model.R = ...
end